# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = [
  "github.com/gogo/protobuf/proto",
  "github.com/gogo/protobuf/jsonpb",
  "github.com/gogo/protobuf/protoc-gen-gogoslick",
  "github.com/gogo/protobuf/gogoproto",
]

ignored = [
  # Context Graph depends on a locally vendored library that isn't (yet) available upstream.
  "istio.io/contrib/adapters/stackdriver/contextgraph",
]

[[override]]
  name = "istio.io/istio"
  branch = "master"

[[constraint]]
branch = "master"
name = "google.golang.org/genproto"