apiVersion: "config.istio.io/v1alpha2"
kind: example
metadata:
  name: handler
  namespace: istio-system
spec:

---
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: instance
  namespace: istio-system
spec:

---
apiVersion: "config.istio.io/v1alpha2"
kind: reportnothing
metadata:
  name: instance
  namespace: istio-system
spec:

---
apiVersion: "config.istio.io/v1alpha2"
kind: examplereport
metadata:
  name: instance
  namespace: istio-system
spec:
  variables:
    source_service: source.service | "unknown"
    source_version: source.labels["version"] | "unknown"
    destination_service: destination.service | "unknown"
    destination_version: destination.labels["version"] | "unknown"
    response_code: response.code | 200
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: examplerule
  namespace: istio-system
spec:
  match: "true" # match for all requests
  actions:
  - handler: handler.example.istio-system
    instances:
    - instance.checknothing
    - instance.reportnothing
    - instance.examplereport
