apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stackdriveradapter
  namespace: istio-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stackdriveradapter
        version: v1
    spec:
      containers:
      - image: {HUB}/stackdriveradapter:{TAG}
        imagePullPolicy: Always
        name: stackdriveradapter
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: stackdriveradapter
  namespace: istio-system
  labels:
    app: stackdriveradapter
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: stackdriveradapter
---
